language: java
jdk:
  - oraclejdk8
script: "mvn cobertura:cobertura"
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 0d79f169-c436-4dff-a869-fd38680b0a66
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/cobertura/coverage.xml -t a2eff6ad9525465d99025e231ea60ef9